match_by: sensor_id
daily_output: true
calc_groups:
  1: true
  2: true
  3: true
  4: true
  5: true
  6: true
  7: true
  8: true
mode: 0
duringday: 14
interimday: 8
patient_list_file: D:\LifanDataClaudeCode\CGM_DRQ_260618_R\requestall.csv
data_folder: D:\LifanDataClaudeCode\CGM_DRQ_260618_R\02_OriginalData\CGMOriginalDataAll_260331
output_folder: D:\LifanDataClaudeCode\CGM_DRQ_260618_R\00_Results
datetag: DRQ260618
nametag: Daily_D1-14
output_filename_template: CGM_{datetag}_{nametag}_Mode{mode}_Results.xlsx
